[package]
name = "yyx-equip"
version = "0.1.0"
authors = ["Flux Xu <fluxxu@gmail.com>"]
edition = "2018"

[dependencies]
yyx-types = { path = "../yyx-types" }
serde_json = "1.0"
crossbeam-channel = "0.3.9"
rand = "0.7.2"
ordered-float = "2.0.1"