CREATE TABLE player (
  id INTEGER PRIMARY KEY NOT NULL,
  short_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  level INTEGER NOT NULL,
  latest_snapshot_date TIMESTAMP NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE equip_group (
  id INTEGER PRIMARY KEY NOT NULL,
  player_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  equip_ids TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  FOREIGN KEY(player_id) REFERENCES player(id)
);

CREATE TABLE equip_ref (
  id INTEGER PRIMARY KEY NOT NULL,
  player_id INTEGER NOT NULL,
  yys_id TEXT NOT NULL,
  suit_id INTEGER NOT NULL,
  pos INTEGER NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  FOREIGN KEY(player_id) REFERENCES player(id)
);

CREATE TABLE hero_ref (
  id INTEGER PRIMARY KEY NOT NULL,
  player_id INTEGER NOT NULL,
  yys_id TEXT NOT NULL,
  hero_id INTEGER NOT NULL,
  nick_name TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  FOREIGN KEY(player_id) REFERENCES player(id)
);

CREATE TABLE equip_preset_ref (
  id INTEGER PRIMARY KEY NOT NULL,
  player_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  equip_ids TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  FOREIGN KEY(player_id) REFERENCES player(id)
);

CREATE TABLE tag (
  id INTEGER PRIMARY KEY NOT NULL,
  player_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  exclude_from_equip_calc BOOLEAN DEFAULT FALSE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  FOREIGN KEY(player_id) REFERENCES player(id)
);

CREATE TABLE tag_object (
  id INTEGER PRIMARY KEY NOT NULL,
  tag_id INTEGER NOT NULL,
  object_type INTEGER NOT NULL,
  object_id INTEGER NOT NULL,
  FOREIGN KEY(tag_id) REFERENCES tag(id)
);
